package com.sajib.recyclerviewwithkotlin

const val apple:String="An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today."
const val banana:String="A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called \"plantains\", distinguishing them from dessert bananas."
const val blackberry:String="The blackberry is an edible fruit produced by many species in the genus Rubus in the family Rosaceae, hybrids among these species within the subgenus Rubus, and hybrids between the subgenera Rubus and Idaeobatus."
const val grape:String="A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis. Grapes are a non-climacteric type of fruit, generally occurring in clusters. The cultivation of grapes began perhaps 8,000 years ago, and the fruit has been used as human food over history."
const val jackfruit:String="Jackfruit is a tropical tree fruit grown in Asia, Africa and South America. It belongs to the same plant family as figs and mulberries. Under its thick, bumpy green rind is a stringy yellow flesh that you can eat raw or cooked in a variety of dishes. (Its seeds are also edible.)"
const val jamrul:String="Syzygium samarangense is a species of flowering plant in the family Myrtaceae, native to an area that includes the Greater Sunda Islands, Malay Peninsula, and the Andaman and Nicobar Islands, but introduced in prehistoric times to a wider area and now widely cultivated in the tropics."
const val Kiwi:String="Kiwifruit or Chinese gooseberry is the edible berry of several species of woody vines in the genus Actinidia. The most common cultivar group of kiwifruit is oval, about the size of a large hen's egg: 5–8 centimetres in length and 4.5–5.5 cm in diameter. "
const val lichi:String="Lichi or litchi fruits are a popular natural bounty in tropical regions, that not only render a delicious flavour to numerous pastries and desserts but also confer a plethora of health benefits. These include uplifting immunity, promoting weight loss, enhancing digestive processes, enriching skin texture besides hydrating the body and relieving mental stress, tension and anxiety.\n" +
        "\n" +
        "Scientifically termed Litchi chinensis, the lychee fruits are the only members of this particular Litchi genus in the Sapindaceae or soapberry family of flowering plants.\n" +
        "\n" +
        "What Is The Meaning Of Lichi?"
const val mango:String="mango, (Mangifera indica), member of the cashew family (Anacardiaceae) and one of the most important and widely cultivated fruits of the tropical world. The mango tree is considered indigenous to southern Asia, especially Myanmar and Assam state of India, and numerous cultivars have been developed. Mangoes are a rich source of vitamins A, C, and D."
const val orange:String="An orange is a fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange."
const val percimon:String="Persimmons are a type of fall fruit, typically in season from September through December. When ripe, they have a yellow-orange flesh, a soft jelly-like texture, and a shape akin to that of a tomato. Their exterior can range in color from pale yellow to a deep, red-orange."
const val sofeda:String="Manilkara zapota, commonly known as sapodilla, sapote, chicozapote, chico, chicle, naseberry, or nispero, among other names, is a long-lived, evergreen tree native to southern Mexico, Central America and the Caribbean."
const val guava:String="guava, (Psidium guajava), small tropical tree or shrub of the family Myrtaceae, cultivated for its edible fruits. Guava trees are native to tropical America and are grown in tropical and subtropical areas worldwide. Guava fruits are processed into jams, jellies, and preserves and are common pastry fillings."